CompileFlags:                     # Tweak the parse settings
  Add: [-xc++, -std=c++20, -Wall]

Diagnostics:
  ClangTidy:
    Remove: bugprone-unchecked-optional-access 

    CheckOptions:
      cppcoreguidelines-avoid-do-while.IgnoreMacros: True

