CompileFlags:
  Add: [-xc++, -std=c++20, -Wall]

Diagnostics:
  UnusedIncludes: Strict

  ClangTidy:
    Remove: [ cppcoreguidelines-avoid-do-while ]

    CheckOptions:
      cppcoreguidelines-avoid-do-while.IgnoreMacros: True

