CompileFlags:                     # Tweak the parse settings
  Add: [-xc++, -std=c++20, -Wall]

Diagnostics:
  UnusedIncludes: Strict

  ClangTidy:
    Remove: [bugprone-unchecked-optional-access,
             bugprone-easily-swappable-parameters,
             cppcoreguidelines-pro-bounds-pointer-arithmetic]

    CheckOptions:
      cppcoreguidelines-avoid-do-while.IgnoreMacros: True

